apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-password
type: Opaque
stringData:
  password: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-username
type: Opaque
stringData:
  username: postgres

---