version: "3"
services:
  postgres:
    image: postgres:13-alpine
    container_name: hostel-booking
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - hostel-booking-network


volumes:
  db-data:

networks:
  hostel-booking-network:
    driver: bridge