server:
  port: 8080

spring:
  mvc:
    format:
      date: dd/MM/yyyy
resilience4j.circuitbreaker:
  configs:
    customs:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
